### ISSUE TITLE
upload to nexus does not use username/pwd from settings.xml file

### ISSUE THREAD

**Issue by janssk1** [kiwigrid/helm-maven-plugin#105]
**Environment (plugin version, maven version, OS, ...)**:
version 5.6

**What happened**:
I was hoping to keep nexus credentials out of our poms. However, for nexus the username/pwd *must* be configured in the plugin. For artifactory, the username/pwd is retrieved from settings.xml if not specified in the pom. It would be good to have the behavior for other repository types as well.

**Comment by thomschke** [comment]
see #101

**Comment by JarnoRFB** [comment]
I think this can be closed after #155 and https://github.com/kiwigrid/helm-maven-plugin/releases/tag/helm-maven-plugin-5.9.

**Comment by janssk1** [comment]
Fixed in 5.9
