### ISSUE TITLE
Do not add helm repo if already configured

### ISSUE THREAD

**Issue by mederel** [kiwigrid/helm-maven-plugin#119]
**This is not a request for help.**:

---

**FEATURE REQUEST**

If on a machine helm has already been configured and repositories added manually to its config, today the maven plugin fails in this way at init step:

```
[INFO] --- helm-maven-plugin:5.6:init (package-chart) @ myproject ---
[INFO] Initializing Helm...
[INFO] Creating output directory...
[INFO] Using local HELM binary [C:\ProgramData\chocolatey\bin\helm.exe]
[INFO] Adding repo [[my-repo / https://repo.url/]]
[ERROR] Error: repository name (my-repo) already exists, please specify a different name
```

The feature is to check for existence of the repository before adding it.

**Comment by vliska** [comment]
Use repositoryConfig -> throw it to target/ directory.

                <repositoryConfig>${project.build.directory}/.config/helm/repositories.yaml</repositoryConfig>

**Comment by mederel** [comment]
> 
> 
> Use repositoryConfig -> throw it to target/ directory.
> 
> ```
>             <repositoryConfig>${project.build.directory}/.config/helm/repositories.yaml</repositoryConfig>
> ```
> 
> Btw - it works if it exists (tells you that repository exists). It fails if it exists with a different URL and same repository name.

Good to know. Thanks for the details!!
