### ISSUE TITLE
Deploying to artifactory using 'groupId' path

### ISSUE THREAD

**Issue by icstreispe** [kiwigrid/helm-maven-plugin#128]
I've created a pom.xml like this:

   ```
<groupId>com.xxx.prj.helm</groupId>
   <artifactId>ui</artifactId>
   <packaging>helm</packaging>
..
<properties>
        <release.url>https://artifactory.xxx.com/artifactory/hlm-all/</release.url>
        <snapshot.url>....</snapshot.url>
    </properties>
...
<plugin>
    <groupId>com.kiwigrid</groupId>
    <artifactId>helm-maven-plugin</artifactId>
    <version>5.6</version>
    <extensions>true</extensions>       <!-- for custom packaging -->
    <configuration>
        <chartVersion>${project.version}</chartVersion>
        <chartDirectory>${project.build.directory}</chartDirectory>

        <useLocalHelmBinary>true</useLocalHelmBinary>
        <autoDetectLocalHelmBinary>true</autoDetectLocalHelmBinary>
        <addDefaultRepo>false</addDefaultRepo>
        <uploadRepoStable>
            <name>hlm-public</name>
            <url>${release.url}</url>
            <type>ARTIFACTORY</type>
        </uploadRepoStable>
        <uploadRepoSnapshot>
            <name>hlm-private</name>
            <url>${snapshot.url></url>
            <type>ARTIFACTORY</type>
        </uploadRepoSnapshot>

    </configuration>
</plugin>
```

Settings.xml is correctly configured.
Then doing `mvn clean deploy`  the plugin tries to deploy to:
https://artifactory.xxx.com/artifactory/hlm-all/ instead of using groupId path and deploying to:
https://artifactory.xxx.com/artifactory/hlm-all/com/xxx/prj/helm/ui/${project.version}/ as I think it should.

1. Is there a way to force it to deploy to the 'groupId' path other than specifying the whole path in the `<release.url>` parameter?
2. Is it possible to remove `<url>` attribute (from `<uploadRepoStable> `tag) so it can only use the `<name>`attribute to correctly identify the repository in the settings.xml in order to do a deploy?

**Comment by nazarovkv** [comment]
Hi @icstreispe 
PR raised: https://github.com/kiwigrid/helm-maven-plugin/pull/134

**Comment by nazarovkv** [comment]
In order to deploy using `groupId` in repo path, add `useGrouId` inside repo configuration. e.g.:
```xml
     <uploadRepoStable>
         <name>hlm-public</name>
         <url>${release.url}</url>
         <type>ARTIFACTORY</type>
         <useGroupId>true</useGroupId>
     </uploadRepoStable>
```

I have just checked inside my organization - works like a charm. 😉

**Comment by icstreispe** [comment]
ok great
how about the second issue?

**Comment by nazarovkv** [comment]
> ok great
> 
> how about the second issue?

I'm not sure that such feature gives much conveniency, since you can always set property in `settings.xml` and reference it from `pom.xml`.

To my mind, it will only give `pom.xml` of smaller size.

But, if you insist, I'll take a look.

**Comment by icstreispe** [comment]
yes it will keep pom.xml smaller/cleaner
if its simple to do it ok, if its too complicated we can forget it....

**Comment by nazarovkv** [comment]
> yes it will keep pom.xml smaller/cleaner
> 
> if its simple to do it ok, if its too complicated we can forget it....
> 
> 

I consider to raise separate issue for this.

**Comment by icstreispe** [comment]
ok

**Comment by nazarovkv** [comment]
Please close this issue. 
I've filed follow-up: https://github.com/kiwigrid/helm-maven-plugin/issues/149
