### ISSUE TITLE
Is plugin maintained somehow?

### ISSUE THREAD

**Issue by nazarovkv** [kiwigrid/helm-maven-plugin#136]
There are mutiple PRs raised, but no reviews/merges/releases done for a long time!

Should community take care of it? Or maintainers will become more active? 
Guys, @axdotl @jekkel what's happening?

**Comment by axdotl** [comment]
It's holiday season. So we are not working, you've to be patient till first or second week of January.

**Comment by nazarovkv** [comment]
Thanks @axdotl!
