### ISSUE TITLE
Unable to use plugin if build system do not have direct access to internet

### ISSUE THREAD

**Issue by dheerajjoshim** [kiwigrid/helm-maven-plugin#19]
Our build system do not have direct external connectivity. To get this plugin to work. We hosted helm 2.9 internally and we are using this plugin. 

However init mojo fails with following error.

`Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: dial tcp 172.217.19.48:443: i/o timeout`

This looks like https://github.com/kubernetes/helm/issues/2864
The solution is to add `--skip-refresh` to init mojo.

Today plugin uses just` --client-only` flag

Mojo code

```
callCli(getHelmExecuteableDirectory()
        + File.separator
        + "helm init --client-only"
        + (StringUtils.isNotEmpty(getHelmHomeDirectory()) ? " --home=" + getHelmHomeDirectory() : ""),
        "Unable to call helm init",
        false);
```

**Comment by axdotl** [comment]
Thanks @dheerajjoshim for this report. We added the skipRefresh option to the plugin, see https://github.com/kiwigrid/helm-maven-plugin/pull/20.

Will become available in version 2.7.
