### ISSUE TITLE
Cannot skip downloading the helm binary

### ISSUE THREAD

**Issue by glockhart** [kiwigrid/helm-maven-plugin#33]
We use this plugin to build our charts in a private network, sometimes with no internet access.

This causes the plugin to fail to build as it can't download the helm binary, even though there's no need for the download as our build machines have the helm binary pre-installed

Skipping the entire init goal isn't an option either as the local repo doesn't get created in that case.

There should be a skipHelmDownload property to allow for this use case

**Comment by axdotl** [comment]
Currently the plugin is not aware of any local helm installations. So it's more a feature request to support local helm bin instead of downloading it.
@glockhart Would you agree?

**Comment by glockhart** [comment]
@axdotl yes, that's one way of looking at it

**Comment by axdotl** [comment]
Solved in v4.0, will become available within the next two hours.
