### ISSUE TITLE
upload to artifactory fails without username/pwd

### ISSUE THREAD

**Issue by janssk1** [kiwigrid/helm-maven-plugin#34]
I'm using an artifactory instance with no username/pwd protection. 
Since the plugin does not find any username/password in settings file, it refuses to upload. 

 Actual behavior: 
[ERROR] Failed to execute goal com.kiwigrid:helm-maven-plugin:3.4:upload (default-upload) on project helm: Execution default-upload of goal com.kiwigrid:helm-maven-plugin:3.4:upload failed: Credentials has to be configured for uploading to Artifactory. -> [Help 1]

Expected behaviour: 
Make the error a warning and continue upload

Workaround is to provide a (dummy) username/pwd in the settings file

**Comment by axdotl** [comment]
Please feel free to create an PR for this.
We will not implement this because we do not have this scenario.
