### ISSUE TITLE
Ability to pass values during linting phase.

### ISSUE THREAD

**Issue by ningthoujam-lokhendro** [kiwigrid/helm-maven-plugin#37]
**Request**: 

---

**FEATURE REQUEST?**:

During the linting phase it would be great to have a configurable tag to pass value.yaml.
This would help to pass during linting while the chart have "required" directive in the templates.

**Environment**:
plugin version: 3.4
Apache Maven 3.6.0 
Java version: 1.8.0_181, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.11.6.el7.x86_64", arch: "amd64", family: "unix"

**How to reproduce it**:
Have any "required" value in the chart template
`thePassword={{ .Values.global.thePassword| required ".Values.global.thePasswordis required" }}`

in value.yaml
`global:
   thePassword:`

then issue linting:
mvn helm:lint

**Comment by axdotl** [comment]
We actually don't won't to support such thing. It's not best practices to work w/ required fields.
Instead a chart should either provide `defaults` or for the password scenario a random password should be created if none set
```
{{- if .Values.global.thePassword }}
  password: {{ .Values.global.thePassword | b64enc | quote }}
{{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
```
