### ISSUE TITLE
Auto detect  helm executable from PATH by default

### ISSUE THREAD

**Issue by masih** [kiwigrid/helm-maven-plugin#38]
**Is this a request for help?**: No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  FEATURE REQUEST

**Environment (plugin version, maven version, OS, ...)**: 
- Plugin Version: `4.0`
- Maven Version: `3.6.0`
- OS: Mac OS X

**What happened**:
By default the plugin would look into the `build.directory/helm` for the executable.

**What you expected to happen**:
If: 
- `useLocalHelmBinary` is set to true, and 
- `helmExecutableDirectory` is not explicitly specified.

then:
- look for `helm` executable in `PATH` first.

This would reduce the adoption barrier, because one does not have to craft the right download URL depending on the local development environment. This is specially cumbersome because the helm download urls use phrases like `darwin`, `amd64`, etc. which is different from `os.name`, `os.arch` system properties as well as [detected](https://github.com/trustin/os-maven-plugin) properties. Which leaves one with having to define profiles for all os/arch permutations.. (not great fun) or use some regex-based property manipulation to get the properties to match the right download URL.

**How to reproduce it** (as minimally and precisely as possible):
Try creating one POM file that would work in both mac and linux systems.

**Anything else we need to know**: Nope that's it I think.

**Comment by axdotl** [comment]
Sounds reasonable. But it may take a while before we can take care of it (because of some other projects).

But you're welcome to create a PR for this :)

**Comment by axdotl** [comment]
Resolved by #38 in v4.1

**Comment by masih** [comment]
@axdotl is the release to Maven central done automatically?

**Comment by axdotl** [comment]
Yes. Will be available within the next two hours.

**Comment by masih** [comment]
Awesome, thank you 🍻
