### ISSUE TITLE
New feature - helm template

### ISSUE THREAD

**Issue by mohitanchlia** [kiwigrid/helm-maven-plugin#40]
This is a FEATURE REQUEST, please:

I am interested in using this plugin and need "helm template" Mojo command as a new feature. I also would like to add --host global environment variable. I have made these changes locally and would like to create a pull request. Let me know how I can contribute.

**Comment by axdotl** [comment]
Hi. Just create a PullRequest from your fork.

**Comment by axdotl** [comment]
Closed due inactivity.
