### ISSUE TITLE
dry-run goal is misnamed

### ISSUE THREAD

**Issue by dallasvaughan** [kiwigrid/helm-maven-plugin#43]
The `dry-run` goal actually just executes `helm install` (without the `--dry-run` parameter), and it successfully installs a release to a locally-running kubernetes cluster.

Shouldn't this be renamed to `install` and perhaps provide parameters to specify `--dry-run` (i.e., as a config parameter like `<dryRun>true</dryRun>`)?

**Comment by axdotl** [comment]
Thanks for the report. It's fixed in 4.3 which is releasing.
