### ISSUE TITLE
Add possibility to use regex in exclude

### ISSUE THREAD

**Issue by JRaver** [kiwigrid/helm-maven-plugin#50]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  FEATURE REQUEST

**Environment (plugin version, maven version, OS, ...)**:
Plugin Version: 4.7
Maven Version: 3.5.3
OS: Linux/MacOs

**What happened**:
We have multiple sub-charts that we want to exclude them from package and lint
```bash
ls -1 istio/charts/
certmanager
istiocoredns
kiali
```

For exclude every chart we need to pass this
 
```xml
<excludes>
<exclude>${project.basedir}/charts/istio/charts/certmanager</exclude>						
<exclude>${project.basedir}/charts/istio/charts/istiocoredns</exclude>
<exclude>${project.basedir}/charts/istio/charts/kiali</exclude>
</excludes>
```

**What you expected to happen**:
It's will be cool if we can pass regexp and make it like this(we tried with "*", ".*", "**" nothing help us)

```xml
<excludes>
<exclude>${project.basedir}/charts/istio/charts/*</exclude>
</excludes>						
```
**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
We must do it because of glibal istio variables 

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/values.yaml#L106

When we make helm lint, in the main Istio helm chart everything works well, but when we trying to do it in Istio sub chart we reach error because these global variables using in sub chart 

https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/charts/tracing/templates/tests/test-tracing-connection.yaml#L1

That's why we want to exclude all these sub-charts in maven plugin

```bash
==> Linting .
[ERROR] templates/: render error in "pilot/templates/serviceaccount.yaml": template: pilot/templates/serviceaccount.yaml:3:14: executing "pilot/templates/serviceaccount.yaml" at <.Values.global.image...>: can't evaluate field imagePullSecrets in type interface {}```

**Comment by axdotl** [comment]
Hi, thanks for this proposal.
We would glad to receive a PR for this.

**Comment by vasilievip** [comment]
@axdotl PR is created, can we get it reviewed, merged and released?

**Comment by axdotl** [comment]
4.8 released - will become available within next two hours at maven central.
