### ISSUE TITLE
301 causes silent failure

### ISSUE THREAD

**Issue by glockhart** [kiwigrid/helm-maven-plugin#52]
**Is this a request for help?**:
Yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Our artifactory based chart repo instance recently started requiring https.  All the old http URL's now return a 301 redirect to the new URL.  This works fine for cases where we're downloading helm charts.

The old URL is http://..... and the new URL is https://.... 
The UploadMojo uses HttpUrlConnection, which doesn't automatically follow redirects when the URL scheme changes.  

When deploying helm charts to artifactory using the helm-maven-plugin it's silently ignoring the 301 redirect.

Snippet from our build log.
`
14:11:52 [main] INFO com.kiwigrid.helm.maven.plugin.UploadMojo - Uploading <**redacted**>...
14:11:52 [main] INFO com.kiwigrid.helm.maven.plugin.UploadMojo - 301 - <html>
14:11:52 <head><title>301 Moved Permanently</title></head>
14:11:52 <body bgcolor="white">
14:11:52 <center><h1>301 Moved Permanently</h1></center>
14:11:52 <hr><center>nginx/1.12.2</center>
14:11:52 </body>
14:11:52 </html>
14:11:52 
`

After this, the artifact hasn't been updated but the build is reporting as successful.

**Environment (plugin version, maven version, OS, ...)**:
plugin version: 4.0
maven version: 3.3.3 and 3.5.4 (these are the only versions I've tested with)
OS: RHEL 7.x, 

**What happened**:
The plugin failed to upload the artifact and didn't fail the build.

**What you expected to happen**:
The plugin should ideally follow the redirect *or* it should indicate an error

**How to reproduce it** (as minimally and precisely as possible):
Try to deploy an artifact to any server that tries to redirect a new location

**Anything else we need to know**:

**Comment by kan-izh** [comment]
That could be closed now.
