### ISSUE TITLE
Add repo fails on windows

### ISSUE THREAD

**Issue by andrejpetras** [kiwigrid/helm-maven-plugin#54]
I am using the local binary

```
<useLocalHelmBinary>true</useLocalHelmBinary>
```
```
[ERROR] Failed to execute goal com.kiwigrid:helm-maven-plugin:4.8:init (package) on project hello-jaxrs: Error processing command
 [C:\projects\hello-jaxrs\target/helm\helm repo add helm-repo https://************/repository/helm/ --username=************--password=************]: 
Cannot run program "C:\projects\hello-jaxrs\target/helm\helm": 
CreateProcess error=2, The system cannot find the file specified -> [Help 1]
```

**Comment by andrejpetras** [comment]
In the source code https://github.com/kiwigrid/helm-maven-plugin/blob/2759d3908d1889f24627f1e6dac183c48e9a6a3e/src/main/java/com/kiwigrid/helm/maven/plugin/InitMojo.java#L68

should not be like?

https://github.com/kiwigrid/helm-maven-plugin/blob/2759d3908d1889f24627f1e6dac183c48e9a6a3e/src/main/java/com/kiwigrid/helm/maven/plugin/InitMojo.java#L147

**Comment by axdotl** [comment]
Hi @andrejpetras, we will have a closer look on this.
In the meantime you could try to explicit set `<helmExecutableDirectory>` to get your build working (at least locally).

**Comment by axdotl** [comment]
4.9 is on its way.
