### ISSUE TITLE
Adding default repo breaks plugin for companies sitting behind a proxy

### ISSUE THREAD

**Issue by papanito** [kiwigrid/helm-maven-plugin#68]
**Is this a BUG REPORT **

**Environment (plugin version, maven version, OS, ...)**:

- Plugin Version: 5.0
- Maven Version: 3.6.0
- OS: Linux

**What happened**:

Our build slaves do not have a connection to the internet but rather do we use a proxy repo (Artifactory) for maven. Using version 5.0 breaks the usage of the plugin cause it does add the `stable` helm repo by default which points to `https://kubernetes-charts.storage.googleapis.com"` 

https://github.com/kiwigrid/helm-maven-plugin/blob/master/src/main/java/com/kiwigrid/helm/maven/plugin/InitMojo.java#L78

```bash
03:11:24  [INFO] --- helm-maven-plugin:5.0:init (default-init) @ acquiring-services ---
03:11:24  [INFO] Initializing Helm...
03:11:24  [INFO] Creating output directory...
03:11:24  [INFO] Using local HELM binary [/usr/local/bin/helm]
03:11:24  [INFO] Adding default repo [stable]
03:13:46  [ERROR] Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Get https://kubernetes-charts.storage.googleapis.com/index.yaml: proxyconnect tcp: dial tcp  x.x.x.x: connect: connection timed out
```

**What you expected to happen**:

The plugin shall not any default repo unless it is explicitly configured that way

**How to reproduce it** (as minimally and precisely as possible):

1. Block connection to internet from your build machine
2. Run `mvn compile`

**Anything else we need to know**:

N/A

**Comment by papanito** [comment]
Thanks, that was quick!

**Comment by axdotl** [comment]
You're welcome!
But it might takt up to 2 hours until it will available via maven central.
