### ISSUE TITLE
Question: Is there support for overriding chart values (e.g. --set <key=value>) in package phase??

### ISSUE THREAD

**Issue by cr-kobyisrael** [kiwigrid/helm-maven-plugin#74]
We have a use-case where we need to override some of the chart values, this is done using --set flag, is this plugin support such feature?

**Comment by GovindSynerzip** [comment]
+1

**Comment by kulkarnigovind9** [comment]
+1

**Comment by axdotl** [comment]
Hello, there is no such feature.
To better understand your use-case: Could you please provide more details for which goal do you want to override the default values?

**Comment by kulkarnigovind9** [comment]
Hi @axdotl 
Actually, in my case, I wanted to change the Values for image repo from the CI pipeline as per current pipeline branch/parameters, as we have different image repositories for different environments. We generally tag the docker image as per the environment repository and wanted to use the same URL to be used as image repo parameter value in values.yaml file.
