### ISSUE TITLE
Automatically download right helm binaries depends on the platform and version 

### ISSUE THREAD

**Issue by foal** [kiwigrid/helm-maven-plugin#75]
**FEATURE REQUEST**

Automatically download right binaries depends on the platform and version. 

In the plugin configuration specify only helm version and allows to plugin automatically select appropriate helm binaries and download them.

**Comment by axdotl** [comment]
Hi @foal ,

what would be the benefit for the user from your point of view?

**Comment by jekkel** [comment]
@axdotl we did this for the [helm gradle plugin](https://github.com/kiwigrid/helm-gradle-plugin) and it's a convenience feature which means less required config for users.

**Comment by foal** [comment]
@axdotl - I develop on Windows, CI is running on Linux/docker (not only AMD64). So without auto-selection, I need to use the local binaries or complicated configuration.

**Comment by blindenvy** [comment]
This can be handled by taking advantage of profiles in your maven project, yes it's more configuration, but not that complicated. For example:
```
	<profiles>
		<profile>
			<id>nix</id>
			<activation>
				<os>
					<family>unix</family>
					<name>Linux</name>
				</os>
			</activation>
			<properties>
				<helmDownloadUrl>https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz</helmDownloadUrl>
			</properties>
		</profile>
		<profile>
			<id>mac</id>
			<activation>
				<os>
					<family>mac</family>
					<arch>x86_64</arch>
				</os>
			</activation>
			<properties>
				<helmDownloadUrl>https://get.helm.sh/helm-v3.1.1-darwin-amd64.tar.gz</helmDownloadUrl>
			</properties>
		</profile>
	</profiles>
```

I do agree, it would be nice for this to automatically be handled, and we only need to support listing the version of helm we want to be downloaded (IE. `3.1.1`).
