### ISSUE TITLE
Version and name discrepancy from pom.xml and Chart.yaml

### ISSUE THREAD

**Issue by papanito** [kiwigrid/helm-maven-plugin#85]
**Is this a request for help?**:

This is my `pom.yml` which defines `chartVersion`  to use the `project.version`

```
....
    <groupId>ch.mycompany</groupId>
    <artifactId>helm-chart-test</artifactId>
    <version>1.0.0-SNAPSHOT</version>
...
    <build>
        <plugins>
            <plugin>
                <groupId>com.kiwigrid</groupId>
                <artifactId>helm-maven-plugin</artifactId>
                <version>5.4</version>
                <configuration>
                    <chartVersion>${project.version}</chartVersion>
...
```

And this is my `Chart.yaml` which also specifies the version

```
apiVersion: v1
appVersion: "1.0"
description: Test Helm chart
name: test
version: 0.1.0
```

When running maven takes the version from the `pom.xml` into the artifact name which is created. Thus I will get the following artifact

```
nessie-1.0.0-SNAPSHOT.tgz
```

So there is a mismatch between the version from `pom.xml` and `Chart.yaml` (so the chart artifact uses `1.0.0-SNAPSHOT` whereas in the `Chart.yaml` packaged into the artifact will contain `0.1.0`.

What is the best workflow in your opinion to make that consistent? Manually ensure that the version in the `Chart.yaml` is actually `1.0.0`? 

Would it make sense if the plugin would actually use `project.artifactId` and `project.version` to be automatically propagated to the Chart.yaml?

**Comment by axdotl** [comment]
You could use following line in your `Chart.yaml`:
```
version: ${project.version}
```

Then use the `maven-resource-plugin` to process and filter the resources before running the `helm-maven-plugin`.

See #78 for an example configuration.

Feel free to re-open the issue, if needed.

**Comment by papanito** [comment]
OK I thought so and I guess that's fine

As far as I think this approach has one downside: You cannot do `helm install` or `helm package` from your the chart directory but you always need to have to use a package. Same problem arises when you want to do gitops and deploy directly from source control - but then you probably do not necessarily need the package artifact...
