### ISSUE TITLE
Feature: Execute 'template' command to verify a chart

### ISSUE THREAD

**Issue by sishbi** [kiwigrid/helm-maven-plugin#86]
FEATURE REQUEST

When developing complex charts and helpers it useful to be able to render the template
to verify whether the template is valid YAML/JSON.
I currently have to do this manually but I think this would be a useful enhancement to the plugin.
This is almost like a unit test as I have written a dummy chart with templates that use the helper functions and then I am running 'helm template' passing the dummy chart and a symlinked copy of the helper chart.

**Environment (plugin version, maven version, OS, ...)**:
Plugin version: 5.4
Maven version: 3.6.3
OS: macOS 10.14.6

**Comment by sishbi** [comment]
Note: I can't use 'dry-run' as I do not have a k8s cluster on my Mac machine where I am developing the charts...

**Comment by axdotl** [comment]
Got your point. Please feel free to create a PR for this :)
In the meantime KIND (https://kind.sigs.k8s.io) might be helpful for your local setup.

**Comment by jekkel** [comment]
You might want to have a look at our [gradle plugin for some inspiration](https://github.com/kiwigrid/helm-gradle-plugin#author-tests).

**Comment by rvesse** [comment]
You might also find https://github.com/quintush/helm-unittest relevant, we actually use this in our CICD pipelines heavily to validate charts.

Unfortunately you can't invoke Helm plugins using this plugin currently, I have been playing around with adding the ability to invoke Helm plugins by extending this plugin and should have a PR for this later this week
