### ISSUE TITLE
Chart Version optional

### ISSUE THREAD

**Issue by marcoslarsen** [kiwigrid/helm-maven-plugin#94]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Environment (plugin version, maven version, OS, ...)**:
Version 5.5

**What happened**:
I'm executing the package and upload goals, but I'd like to not enforce the chartVersion and keep the version already set on the Chart.yaml but the chartVersion property is required and always applied. Could there be a way to not enforce the chartVersion property?

**What you expected to happen**:
- chartVersion property not required.
- helm package and upload with the chart version defined on the Chart.yaml

**How to reproduce it** (as minimally and precisely as possible):
- mvn helm:package with plugin configuration without chartVersion.

**Anything else we need to know**:

**Comment by marcoslarsen** [comment]
Added a draft pull request with what I'm suggesting: https://github.com/kiwigrid/helm-maven-plugin/pull/95

**Comment by fabian-schlegel** [comment]
Integrated in 5.6
