### ISSUE TITLE
New Repo Type Nexus

### ISSUE THREAD

**Issue by dangllucas** [kiwigrid/helm-maven-plugin#96]
**Is this a request for help?**: Not really

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Environment (plugin version, maven version, OS, ...)**: 5.5, 3.6.3, MacOS

**What happened**: Tried Upload to Nexus Helm Repository --> Failed --> Upload to Nexus need PUT and File Name in URL

**What you expected to happen**: An Error Actually

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**: PR is on its way

**Comment by fabian-schlegel** [comment]
Integrated in 5.6
